# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
name = "Grocom"
client_id = "192fed02beba7002e96ee77ff95cdb1e"
application_url = "https://fe-gearo.vinetawp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_third_party_fulfillment_orders,read_third_party_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_order_edits,write_order_edits,write_orders,read_orders,read_price_rules,read_products,read_themes,write_price_rules,read_content,write_content"

[auth]
redirect_urls = [
  "https://be-gearo.vinetawp.com/api/exchange-token/callback"
]

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://be-gearo.vinetawp.com/api/webhook/customers/data_request"


[pos]
embedded = false

[build]
dev_store_url = "demo-gearo.myshopify.com"

